CREATE TABLE template_fields (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id                 BIGINT       NOT NULL,
    parent_id                   BIGINT,
    field_name                  VARCHAR(255) NOT NULL,
    xml_name                    VARCHAR(255) NOT NULL,
    display_name                VARCHAR(255),
    node_type                   VARCHAR(20)  NOT NULL,
    value_type                  VARCHAR(50),
    source_type                 VARCHAR(20),
    occurrence_rule             VARCHAR(30),
    empty_handling              VARCHAR(30)  NOT NULL,
    required_when_parent_exists BOOLEAN      NOT NULL DEFAULT false,
    trigger_activation          BOOLEAN,
    default_value               TEXT,
    static_value                TEXT,
    xml_path                    VARCHAR(1000),
    namespace                   VARCHAR(255),
    display_order               INTEGER      NOT NULL,
    description                 TEXT,
    created_at                  TIMESTAMPTZ  NOT NULL,
    updated_at                  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_template_fields_template
        FOREIGN KEY (template_id) REFERENCES templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_template_fields_parent
        FOREIGN KEY (parent_id) REFERENCES template_fields (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_template_fields_template_parent_field_name
    ON template_fields (template_id, COALESCE(parent_id, 0::bigint), field_name);

CREATE UNIQUE INDEX uk_template_fields_template_parent_display_order
    ON template_fields (template_id, COALESCE(parent_id, 0::bigint), display_order);

CREATE INDEX idx_template_fields_template_id ON template_fields (template_id);
CREATE INDEX idx_template_fields_parent_id ON template_fields (parent_id);
CREATE INDEX idx_template_fields_template_display_order ON template_fields (template_id, display_order);

CREATE TABLE template_mappings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id          BIGINT      NOT NULL,
    template_field_id    BIGINT      NOT NULL,
    master_data_field_id BIGINT,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_template_mappings_template
        FOREIGN KEY (template_id) REFERENCES templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_template_mappings_template_field
        FOREIGN KEY (template_field_id) REFERENCES template_fields (id) ON DELETE CASCADE,
    CONSTRAINT fk_template_mappings_master_data_field
        FOREIGN KEY (master_data_field_id) REFERENCES master_data_fields (id) ON DELETE SET NULL,
    CONSTRAINT uk_template_mappings_template_field
        UNIQUE (template_field_id)
);

CREATE INDEX idx_template_mappings_template_id ON template_mappings (template_id);
CREATE INDEX idx_template_mappings_master_data_field_id ON template_mappings (master_data_field_id);
