CREATE TABLE saved_inputs (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id              BIGINT        NOT NULL,
    user_id                   BIGINT        NOT NULL,
    template_id               BIGINT        NOT NULL,
    input_data_json           JSONB         NOT NULL,
    selected_master_data_json JSONB,
    created_at                TIMESTAMPTZ   NOT NULL,
    updated_at                TIMESTAMPTZ   NOT NULL,
    expired_at                TIMESTAMPTZ,
    CONSTRAINT fk_saved_inputs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
    CONSTRAINT fk_saved_inputs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_saved_inputs_template FOREIGN KEY (template_id) REFERENCES templates (id) ON DELETE CASCADE,
    CONSTRAINT uk_saved_inputs_workspace_user_template UNIQUE (workspace_id, user_id, template_id)
);

CREATE INDEX idx_saved_inputs_workspace_id ON saved_inputs (workspace_id);
CREATE INDEX idx_saved_inputs_user_id ON saved_inputs (user_id);
CREATE INDEX idx_saved_inputs_template_id ON saved_inputs (template_id);
