CREATE TABLE templates (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(100)  NOT NULL,
    name                 VARCHAR(255)  NOT NULL,
    description          TEXT,
    status               VARCHAR(20)   NOT NULL,
    compiled_schema_json JSONB,
    -- Foreign key to users(id) is intentionally deferred until the users table is introduced.
    created_by           BIGINT        NOT NULL,
    created_at           TIMESTAMPTZ   NOT NULL,
    updated_at           TIMESTAMPTZ   NOT NULL,
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT uk_templates_code UNIQUE (code)
);

CREATE INDEX idx_templates_status ON templates (status);
