CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    is_admin      BOOLEAN       NOT NULL DEFAULT false,
    is_active     BOOLEAN       NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ   NOT NULL,
    updated_at    TIMESTAMPTZ   NOT NULL,
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_users_is_active ON users (is_active);
