CREATE TABLE master_data_fields (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_data_type_id BIGINT       NOT NULL,
    field_name          VARCHAR(255) NOT NULL,
    name                VARCHAR(255) NOT NULL,
    data_type           VARCHAR(50)  NOT NULL,
    is_required         BOOLEAN      NOT NULL DEFAULT false,
    display_order       INTEGER      NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_master_data_fields_type
        FOREIGN KEY (master_data_type_id) REFERENCES master_data_types (id),
    CONSTRAINT uk_master_data_fields_type_field_name
        UNIQUE (master_data_type_id, field_name)
);

CREATE INDEX idx_master_data_fields_type_id ON master_data_fields (master_data_type_id);
