CREATE TABLE master_data_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_data_type_id BIGINT       NOT NULL,
    data_json           JSONB        NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_master_data_records_type
        FOREIGN KEY (master_data_type_id) REFERENCES master_data_types (id)
);

CREATE INDEX idx_master_data_records_type_id ON master_data_records (master_data_type_id);
CREATE INDEX idx_master_data_records_json ON master_data_records USING GIN (data_json);
